import React, { useEffect, useState } from 'react';
import { BackHandler, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { StatusBar } from 'expo-status-bar';
import { lessons, Lesson } from './src/lessons';
type Saved = { completed: string[]; favorites: string[]; drafts: Record<string,string> };
const initial: Saved = {completed:[], favorites:[], drafts:{}};
const tabs=['Accueil','Parcours','Favoris','Progrès'] as const;
export default function App(){return <SafeAreaProvider><LearningApp/></SafeAreaProvider>}
function LearningApp(){
 const [saved,setSaved]=useState<Saved>(initial),[ready,setReady]=useState(false),[error,setError]=useState('');
 const [tab,setTab]=useState<typeof tabs[number]>('Accueil'),[lesson,setLesson]=useState<Lesson|null>(null),[answer,setAnswer]=useState<number|null>(null);
 useEffect(()=>{AsyncStorage.getItem('declic:v1').then(raw=>{if(raw){const d=JSON.parse(raw);if(!Array.isArray(d.completed)||!Array.isArray(d.favorites)||!d.drafts||typeof d.drafts!=='object')throw Error();setSaved(d)}}).catch(()=>setError('Sauvegarde indisponible. Les changements resteront limités à cette session.')).finally(()=>setReady(true))},[]);
 useEffect(()=>{if(!ready||error)return;const t=setTimeout(()=>{AsyncStorage.setItem('declic:v1',JSON.stringify(saved)).catch(()=>setError('Sauvegarde indisponible. Les changements restent dans cette session.'))},300);return()=>clearTimeout(t)},[saved,ready,error]);
 useEffect(()=>{const s=BackHandler.addEventListener('hardwareBackPress',()=>{if(lesson){setLesson(null);return true}if(tab!=='Accueil'){setTab('Accueil');return true}return false});return()=>s.remove()},[lesson,tab]);
 const open=(l:Lesson)=>{setAnswer(null);setLesson(l)};
 const next=lessons.find(l=>!saved.completed.includes(l.id));
 const button=(label:string,action:()=>void,light=false)=><Pressable accessibilityRole="button" onPress={action} style={({pressed})=>[s.button,light&&s.light,pressed&&{opacity:0.7}]}><Text style={[s.buttonText,light&&{color:'#193D37'}]}>{label}</Text></Pressable>;
 const card=(l:Lesson)=><Pressable accessibilityRole="button" key={l.id} onPress={()=>open(l)} style={s.card}><Text style={s.eyebrow}>{l.tag} · {l.minutes} MIN</Text><Text style={s.cardTitle}>{l.title}</Text><Text style={s.muted}>{saved.completed.includes(l.id)?'Terminé · Revoir':'Découvrir la leçon →'}</Text></Pressable>;
 if(!ready)return <SafeAreaView style={s.safe}><Text style={s.title}>Déclic IA</Text><Text>Préparation de votre parcours…</Text></SafeAreaView>;
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.top}><Text style={s.brand}>déclic ia.</Text><Text style={s.eyebrow}>À VOTRE RYTHME</Text></View>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}<ScrollView key={lesson?.id||tab} keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>
 {lesson?<>{button('← Retour',()=>setLesson(null),true)}<Text style={s.eyebrow}>{lesson.tag} · {lesson.minutes} MIN</Text><Text style={s.title}>{lesson.title}</Text><Text style={s.body}>{lesson.body}</Text><View style={s.example}><Text style={s.eyebrow}>UNE DEMANDE À ESSAYER</Text><Text selectable style={s.body}>{lesson.example}</Text></View>
 {button(saved.favorites.includes(lesson.id)?'Retirer des favoris':'Garder dans mes favoris',()=>setSaved(d=>({...d,favorites:d.favorites.includes(lesson.id)?d.favorites.filter(id=>id!==lesson.id):[...d.favorites,lesson.id]})),true)}
 <Text style={s.heading}>À vous de jouer</Text><Text style={s.body}>{lesson.challenge}</Text><TextInput accessibilityLabel="Votre demande d’entraînement" multiline placeholder="Écrivez votre demande ici…" style={s.input} value={saved.drafts[lesson.id]||''} onChangeText={text=>setSaved(d=>({...d,drafts:{...d.drafts,[lesson.id]:text}}))}/><Text style={s.muted}>Brouillon personnel enregistré sur cet appareil. Il n’est pas envoyé à une IA et n’est pas noté.</Text><Text style={s.heading}>Vérifiez votre compréhension</Text><Text style={s.body}>{lesson.question}</Text>{lesson.options.map((opt,i)=><Pressable key={opt} accessibilityRole="radio" accessibilityState={{checked:answer===i}} onPress={()=>setAnswer(i)} style={[s.option,answer===i&&s.selected]}><Text style={s.body}>{opt}</Text></Pressable>)}
 {answer!==null&&<View accessibilityLiveRegion="polite" style={s.example}><Text style={s.cardTitle}>{answer===lesson.answer?'Bien vu !':'Essayez encore'}</Text><Text style={s.body}>{answer===lesson.answer?lesson.explanation:'Relisez la leçon et choisissez une autre réponse.'}</Text></View>}{answer===lesson.answer&&button('Valider cette leçon',()=>{setSaved(d=>({...d,completed:[...new Set([...d.completed,lesson.id])]}));setLesson(null)})}</>:<>
 {tab==='Accueil'&&<><Text style={s.eyebrow}>UN PETIT PAS, CHAQUE JOUR</Text><Text style={s.title}>L’IA devient utile.{'\n'}Vous gardez la main.</Text><Text style={s.body}>Apprenez à utiliser ChatGPT pour les choses qui comptent au quotidien.</Text><View style={s.hero}><Text style={s.heroSmall}>VOTRE PROCHAIN DÉCLIC</Text><Text style={s.heroTitle}>{next?.title||'Bravo, les bases sont acquises !'}</Text><Text style={s.heroSmall}>{next?`${next.minutes} minutes · Un exemple · Un exercice`:'Continuez à vous entraîner à votre rythme.'}</Text>{button(next?'Commencer la leçon':'Revoir le parcours',()=>next?open(next):setTab('Parcours'),true)}</View><Text style={s.heading}>Les premiers réflexes</Text>{lessons.slice(0,2).map(card)}</>}
 {tab==='Parcours'&&<><Text style={s.eyebrow}>DÉBUTANT · 6 LEÇONS</Text><Text style={s.title}>Les premiers déclics</Text><Text style={s.body}>Aucune connaissance technique nécessaire. Choisissez une leçon et passez à la pratique.</Text>{lessons.map(card)}</>}
 {tab==='Favoris'&&<><Text style={s.title}>À garder sous la main</Text><Text style={s.body}>Vos exemples utiles au même endroit.</Text>{saved.favorites.length?lessons.filter(l=>saved.favorites.includes(l.id)).map(card):<View style={s.card}><Text style={s.cardTitle}>Votre collection commence ici</Text><Text style={s.body}>Ouvrez une leçon et gardez son exemple dans vos favoris.</Text>{button('Explorer les leçons',()=>setTab('Parcours'))}</View>}</>}
 {tab==='Progrès'&&<><Text style={s.eyebrow}>VOTRE PARCOURS</Text><Text style={s.title}>Chaque déclic compte.</Text><View style={s.card}><Text style={s.score}>{saved.completed.length}/{lessons.length}</Text><Text style={s.body}>leçons validées</Text><View accessibilityRole="progressbar" accessibilityValue={{min:0,max:lessons.length,now:saved.completed.length}} style={s.track}><View style={[s.fill,{width:`${saved.completed.length/lessons.length*100}%`}]}/></View></View><Text style={s.body}>Une leçon est validée après une bonne réponse au quiz. Prenez aussi le temps de réaliser son exercice.</Text><Text style={s.heading}>Vos données</Text><Text style={s.body}>Progression, favoris et brouillons restent sur ce téléphone. La synchronisation entre appareils n’est pas activée.</Text></>}
 <Text style={s.footer}>Formation indépendante, non affiliée à OpenAI. Les fonctions de ChatGPT varient selon le compte et évoluent. Ressource pédagogique : learn.chatgpt.com/docs/prompting</Text></>}
 </ScrollView>{!lesson&&<View style={s.tabs}>{tabs.map(t=><Pressable key={t} accessibilityRole="tab" accessibilityState={{selected:tab===t}} onPress={()=>setTab(t)} style={s.tab}><Text style={[s.tabText,tab===t&&s.active]}>{t}</Text>{tab===t&&<View style={s.dot}/>}</Pressable>)}</View>}</SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F7F0'},top:{paddingHorizontal:24,paddingVertical:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},brand:{fontSize:28,fontWeight:'800',color:'#193D37'},content:{padding:24,gap:18,maxWidth:720,width:'100%',alignSelf:'center',paddingBottom:40},title:{fontSize:35,lineHeight:42,fontWeight:'800',color:'#193D37'},heading:{fontSize:23,fontWeight:'700',color:'#193D37',marginTop:12},body:{fontSize:17,lineHeight:26,color:'#334E47'},eyebrow:{fontSize:10,fontWeight:'700',letterSpacing:1.1,color:'#47675C'},hero:{backgroundColor:'#193D37',borderRadius:26,padding:26,gap:20},heroTitle:{fontSize:28,lineHeight:35,fontWeight:'700',color:'#FFF'},heroSmall:{fontSize:13,lineHeight:20,color:'#D2EBDD'},button:{padding:16,borderRadius:14,backgroundColor:'#193D37',minHeight:50,alignItems:'center'},light:{backgroundColor:'#E4EEDD'},buttonText:{fontSize:16,fontWeight:'700',color:'#FFF'},card:{padding:22,borderWidth:1,borderColor:'#DCE2D7',backgroundColor:'#FFF',borderRadius:22,gap:14},cardTitle:{fontSize:21,lineHeight:28,color:'#193D37',fontWeight:'700'},muted:{fontSize:13,lineHeight:20,color:'#5C7067'},example:{backgroundColor:'#E7EEDF',padding:22,borderRadius:20,gap:12},input:{minHeight:130,textAlignVertical:'top',backgroundColor:'#FFF',padding:18,borderRadius:16,borderWidth:1,borderColor:'#8CA398',fontSize:17,lineHeight:25,color:'#193D37'},option:{padding:18,borderWidth:1,borderColor:'#BBCABD',borderRadius:16,backgroundColor:'#FFF'},selected:{borderColor:'#23765E',borderWidth:2,backgroundColor:'#E7EEDF'},tabs:{flexDirection:'row',borderTopWidth:1,borderColor:'#DCE2D7',paddingVertical:8,backgroundColor:'#FFF'},tab:{flex:1,minHeight:52,alignItems:'center',justifyContent:'center',gap:7},tabText:{fontSize:13,color:'#586E65'},active:{color:'#193D37',fontWeight:'800'},dot:{width:5,height:5,borderRadius:3,backgroundColor:'#23765E'},score:{fontSize:64,color:'#193D37',fontWeight:'800'},track:{height:10,borderRadius:5,backgroundColor:'#E2E9DD',overflow:'hidden'},fill:{height:10,backgroundColor:'#23765E'},footer:{fontSize:12,lineHeight:18,color:'#65786E',marginTop:24},error:{padding:12,backgroundColor:'#FFE6CE',color:'#713613'}});
